<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
<a href="/01. intro.html">01. intro.html</a>
<a href="/02. new-promise.html">02. new-promise.html</a>
<a href="/03. promise-api.html">03. promise-api.html</a>

<h1>創立自己的 Promise</h1>

<h3>MDN - Promise : <a href="https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Promise">https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Promise</a></h3>

<h4>一個 Promise 物件處於以下幾種狀態：</h4>
<ul>
  <li>擱置（pending）：初始狀態，不是 fulfilled 與 rejected。</li>
  <li>實現（fulfilled）：表示操作成功完成。</li>
  <li>拒絕（rejected）：表示操作失敗了。</li>
</ul>

<img src="./Promise.PNG" alt="" style="width: 600px;">
<img src="./Promise2.PNG" alt="" style="width: 600px;">


<h1>鏈接技巧</h1>
<h3>1. Promise Chain : 執行若失敗直接轉到 .catch 繼續執行 return</h3>
<h3>2. .then 同時接收成功 & 失敗結果, 大多數使用成功結果</h3>

</body>

</html>
<script>

  console.log("Promise:", Promise); // function
  console.dir(Promise);  // 屬性和屬性值

  // 1.
  function sample_newPromise(){
    // 注意 : resolve, reject 一次只會執行其中一個
    const a = new Promise((resolve, reject) => {
      // resolve('success')
      // reject('fail')
    });
    console.log("a:", a);
    
    // a 物件沒辦法傳入參數
    a.then((res)=> {
      console.log("res:", res)
    }).catch((rej) => {
      console.log("rej:", rej)
    })
  }

  
  // 2.
  function sample_fnPromise(){
    // 1. 函式陳述式
    function promiseFn(num) {
      console.log(1);

      return new Promise((resolve, reject) => {
        console.log(2);

        setTimeout(() => {
          if (num) {
            resolve('成功');
          } else {
            reject('失敗')
          }
        }, 1000);
      })
    }

    promiseFn(1)
      .then(res => {
        console.log('then -', res);
      })
      .catch(rej => {
        console.log('catch -', rej);
      })
    
    console.log('程式碼結束');


    // 2. 函式表達式
    const promiseFn2 = () => {
      return new Promise((resolve, reject) => {

      })
    } 

  }







  // ---------- Promise Chain ----------
  function promiseFn(num) {
    return new Promise((resolve, reject) => {

      setTimeout(() => {
        if (num) {
          resolve(`成功 ${num}`);
        } else {
          reject('失敗')
        }
      }, 0);
    })
  }

  // 1. Promise Chain
  function sample_promiseChain(){
    promiseFn(1)
      // 1.
      .then(res => {
          console.log("res:", res);
          return promiseFn(2); // 透過 return 進行串接
        })
      .then(res => {
        console.log("res:", res);
        return promiseFn(3);
      })
      .then(res => {
        console.log("res:", res);
      })


      // 2.
      // .then(res => {
      //   console.log("res:", res);
      //   return promiseFn(0); // 失敗直接轉到 .catch 繼續執行 return
      // })
      // .then(res => {
      //   console.log("res:", res);
      //   return promiseFn(2);
      // })
      // .catch(rej => {
      //   console.log('catch -', rej);
      //   return promiseFn(4);  // 新的Promise行為會屬於另一個鏈
      // })
      // .then(res => {
      //   console.log("res:", res);
      // })
  }


  // 2. then 同時接收成功 & 失敗 結果
  function sample_promiseChain2(){
    promiseFn(0)
      .then(
        (res)=> { // 成功執行 return promiseFn(3)
          console.log('success -', res);
          return promiseFn(3);
        }, (rej)=> {  // 失敗執行 return promiseFn(4)
          console.log('fail -', rej);
          return promiseFn(4);
      })

      .then(
        (res) => {
          console.log('success -', res);
        }, (rej) => {
          console.log('fail -', rej);
      })
  }
</script>